spring.application.name=ILCS-AGENT-AI


spring.ai.mistralai.api-key=v5daQmsLRNu9kcTN6WnqFlBTNzeIDGce
spring.ai.mistralai.chat.enabled=false
spring.ai.mistralai.embedding.options.model=mistral-embed

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create

spring.h2.console.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
